### ISSUE TITLE
iOS: build error due to swift version conflict

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-sdk#14140]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

I've simply created a new empty iOS module and tried to build it. When looking at the trace log I can see:
```
error: failed to build module 'TitaniumKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)', while this compiler is 'Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)'). Please select a toolchain which matches the SDK.
```

Other users had similar issues when building iOS modules too. Is there a way to get rid of it without searching a matching Xcode version?

https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/58656323#58656323 might be a solution (if not already done)

### Expected Behavior

build a module without Xcode/swift error

### Actual behavior

error building

### Reproducible sample

-

### Steps to reproduce

* create a new iOS swift module
* try to build it
* 12.5.0.GA
* Xcode Version 15.1 (15C65)

### Platform

iOS

### SDK version you are using

12.5.0

**Comment by m1ga** [comment]
Ti 12.5.1 with Xcode 16.0 (16A242d) breaks build with 
```
[TRACE] [xcode-dist] <module-includes>:1:9: note: in file included from <module-includes>:1:
[TRACE] [xcode-dist] #import "Headers/TitaniumKit.h"
[TRACE] [xcode-dist]         ^
[TRACE] [xcode-dist] /Users/miga/Library/Application Support/Titanium/mobilesdk/osx/12.5.1.GA/iphone/Frameworks/TitaniumKit.xcframework/ios-arm64/TitaniumKit.framework/Headers/TitaniumKit.h:17:9: error: 'TitaniumKit/TiBase.h' file not found
[TRACE] [xcode-dist] #import <TitaniumKit/TiBase.h>
[TRACE] [xcode-dist]         ^
[TRACE] [xcode-dist] /Users/miga/Library/Application Support/Titanium/mobilesdk/osx/12.5.1.GA/iphone/Frameworks/TitaniumKit.xcframework/ios-arm64/TitaniumKit.framework/Headers/TitaniumKit.h:17:9: note: did not find header 'TiBase.h' in framework 'TitaniumKit' (loaded from '/Users/miga/Library/Developer/Xcode/DerivedData/test_swift-eeqxqbbwfhibfhgudinbgmtmrojt/Build/Intermediates.noindex/ArchiveIntermediates/ComTestSwift/BuildProductsPath/Release-maccatalyst')
[TRACE] [xcode-dist] #import <TitaniumKit/TiBase.h>
[TRACE] [xcode-dist]         ^
[TRACE] [xcode-dist] /Users/miga/test_swift/ios/Classes/ComTestSwiftExampleProxy.swift:10:8: error: could not build Objective-C module 'TitaniumKit'
[TRACE] [xcode-dist] import TitaniumKit
[TRACE] [xcode-dist]        ^
[TRACE] [xcode-dist] SwiftCompile normal x86_64 Compiling\ ComTestSwiftExampleProxy.swift,\ ComTestSwiftModule.swift /Users/miga/test_swift/ios/Classes/ComTestSwiftExampleProxy.swift /Users/miga/test_swift/ios/Classes/ComTestSwiftModule.swift (in target 'ComTestSwift' from project 'test_swift')
```

**Comment by AbdullahFaqeir** [comment]
@m1ga I've already faced this and fixed it, give me this.

**Comment by hbugdoll** [comment]
@m1ga Is the problem still existing?
@AbdullahFaqeir Any update on this?

In https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/58656323#58656323 it was recommended to use the build option `BUILD_LIBRARY_FOR_DISTRIBUTION = YES`.
That was already there, see https://github.com/tidev/titanium-sdk/commit/3242840d191d0258cff227d855f44a98559d2f2e.


```
ti create -p ios --type module --ios-code-base swift
ti build -p ios --build-only --sdk 12.5.0.GA
```
works fine with Xcode 26.
Unfortunately, I currently have no way of testing with predecessor Xcode 15/16.

**Comment by m1ga** [comment]
Have to check it again. Maybe the Swift version of Xcode (https://xcodereleases.com/) and the one from the SDK didn't match at that point.

**Comment by m1ga** [comment]
think we can close this. It works with 13.0.1.GA and I don't think it's recommended to build with an old SDK anymore.
The only small issue I see at the moment is `mac: true` will cause an error and point you to set it to false. Maybe that should be the default setting. But since that is not part of this issue I'll close it

**Comment by hbugdoll** [comment]
@m1ga Thanks for testing again.
